### ISSUE TITLE
xcopy not found

### ISSUE THREAD

**Issue by naamahdaemon** [olton/mina-node-monitor#1]
Hello, 
While trying to build the client (npm run build) on my linux server, got :

```sh
> xcopy client\config.json dist\*.* /Y /I && parcel build -d dist --public-url . --no-minify client/index.html
sh: 1: xcopy: not found
```

Has there ever been a xcopy command on linux ?

Thanks for your reply.

**Comment by olton** [comment]
on Linux you can use command `cp` for file coping

**Comment by naamahdaemon** [comment]
Sure, thank you. I was just wondering why you used xcopy out of the box, but obvioulsy, you run on Windows ;-)
