### ISSUE TITLE
node also restarts while bootstrapping

### ISSUE THREAD

**Issue by gretzke** [olton/mina-node-monitor#6]
restartAfter - value in minutes, if node synced and height is lower from Mina Explorer within the specified time, node will restart after this interval

Currently mina nodes take quite a while to bootstrap. For me it takes longer than 30 minutes at the moment so maybe there should be an exception that the node is not restarted, while its bootstrapping.

**Comment by olton** [comment]
The node may hang in not SYNCED mode, so this rule exists. In 1.0.3 I added the parameter `restartAfterNotSynced` for restarting node in not SYNCED mode by time different from the value in `restartAfter` for a fork. All changes in 1.0.3 can see in https://github.com/olton/mina-node-monitor/blob/1.0.3/CHANGELOG.md (can updatable until release)

**Comment by gretzke** [comment]
What I meant was that when starting the node it goes from Bootstrap > Catchup > Synced. While in the first phase the node was restarted, before even being able to sync completely. So I think it might make sense not to restart the node if its in Bootstrap or Catchup stage.

**Comment by olton** [comment]
I added an exception for BOOTSTRAP state

**Comment by olton** [comment]
fixed
